[package]
name = "beans"
version = "0.1.0"
authors = ["BlackBeans <adrien.mathieu.net@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.9"
hashbrown = "0.9.0"
fixedbitset = "0.3.1"
